#!/usr/bin/env bash
# 1-show_attached_IPs
# This script displays all active IPv4 addresses on the machine

# Loop through all interfaces and print their IPv4 addresses
ip -4 -o addr show | awk '{print $4}' | cut -d/ -f1
